spring:
  jpa:
    properties:
      hibernate:
        jdbc.batch_size: 5000
        generate_statistics: true
        order_inserts: true
  main:
    allow-bean-definition-overriding: true
    web-application-type: none
    
---

spring:
  profiles: mysql
  datasource:
    url: jdbc:mysql://localhost:3306/benchmark
    driverClassName: com.mysql.cj.jdbc.Driver
